version: '3.8'

services:
  discovery:
    build: ./backend/eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_INSTANCE_HOSTNAME=localhost
    networks:
      - event-network

  gateway:
    build: ./backend/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    networks:
      - event-network

  auth-service:
    build: ./backend/auth-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    networks:
      - event-network

  event-service:
    build: ./backend/event-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    networks:
      - event-network

  attendee-service:
    build: ./backend/attendee-service
    ports:
      - "8083:8083"
    depends_on:
      - discovery
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    networks:
      - event-network

  ticket-service:
    build: ./backend/ticket-service
    ports:
      - "8084:8084"
    depends_on:
      - discovery
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    networks:
      - event-network

  notification-service:
    build: ./backend/notification-service
    ports:
      - "8085:8085"
    depends_on:
      - discovery
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    networks:
      - event-network

  analytics-service:
    build: ./backend/analytics-service
    ports:
      - "8086:8086"
    depends_on:
      - discovery
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    networks:
      - event-network

  admin-service:
    build: ./backend/admin-service
    ports:
      - "8087:8087"
    depends_on:
      - discovery
      - event-service
      - auth-service
      - attendee-service
      - ticket-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
    networks:
      - event-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - gateway
    networks:
      - event-network

networks:
  event-network:
    driver: bridge
