server:
  port: 8084

spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:h2:file:/data/ticketdb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true

payhere:
  merchant-id: "4OVyblY3OxU4JH5EsPSamH3PT" # Sandbox App ID
  merchant-secret: "8n3CHVpDyTM4DtRbSNAi5W8bUBU60MMkg8gleLRI8yxu" # Sandbox App Secret
  mode: sandbox

