server:
  port: 8088

spring:
  application:
    name: profile-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://eventmgmt-pg-db.postgres.database.azure.com:5432/postgres?currentSchema=profile_schema&sslmode=require}
    driverClassName: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:postgresadmin}
    password: ${SPRING_DATASOURCE_PASSWORD:EventManagement123!}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        default_schema: ${SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA:profile_schema}
        hbm2ddl:
          create_namespaces: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
  instance:
    preferIpAddress: true

profile:
  avatar:
    storage-path: /data/avatars
    allowed-extensions: jpg,jpeg,png,gif
    max-size-mb: 5

# Springdoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
