server:
  port: 8089

spring:
  application:
    name: review-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://eventmgmt-pg-db.postgres.database.azure.com:5432/postgres?currentSchema=review_schema&sslmode=require}
    driverClassName: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:postgresadmin}
    password: ${SPRING_DATASOURCE_PASSWORD:EventManagement123!}
  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        default_schema: ${SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA:review_schema}
        hbm2ddl:
          create_namespaces: true

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
  instance:
    preferIpAddress: true

# Springdoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Logging
logging:
  level:
    com.eventflow.reviewservice: INFO
    org.springframework.cloud: INFO
