server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:native}
  cloud:
    config:
      server:
        native:
          search-locations: ${SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS:file:./config-repo/}

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:false}
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    registerWithEureka: ${EUREKA_CLIENT_REGISTER:false}
    fetchRegistry: false
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    defaults:
      enabled: true
